"""Added done-column to Todo model

Revision ID: 8910a732063e
Revises: 5ba000de0966
Create Date: 2020-12-05 14:41:42.572906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8910a732063e'
down_revision = '5ba000de0966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'done')
    # ### end Alembic commands ###
